version: "3.1"
services:
  mongo:
    image: pockethepia.azurecr.io/db
    container_name: mongo
    volumes:
        - ./db/data/db:/data/db
    ports:
      - "27017:27017"
  backend:
    image: pockethepia.azurecr.io/backend
    container_name: backend
    depends_on:
      - "mongo"
    ports:
      - "8080:8080"
    environment: 
    - GET_HOSTS_FROM=dns
  frontend:
    image: pockethepia.azurecr.io/frontend
    container_name: frontend
    depends_on:
      - "mongo"
    ports: 
      - "80:80"
      - "443:443"
    environment: 
    - GET_HOSTS_FROM=dns