# TODO add back the build on each service for local deployment
version: "3.1"
services:
  mongo:
    image: gcr.io/pockethepia/pockethepia_db:latest
    container_name: mongo
    volumes:
        - ./db/data/db:/data/db
        - ./db/data/configdb:/data/configdb
    ports:
      - "27017:27017"
  backend:
    image: gcr.io/pockethepia/pockethepia_backend:latest
    container_name: backend
    depends_on:
      - "mongo"
    ports:
      - "8080:8080"
    environment: 
    - GET_HOSTS_FROM=dns
  frontend:
    image: gcr.io/pockethepia/pockethepia_frontend:latest
    container_name: frontend
    depends_on:
      - "mongo"
    ports: 
      - "80:80"
      - "443:443"
    environment: 
    - GET_HOSTS_FROM=dns